import Head from "next/head";
import Analytics from "../components/Analytics";
import Content from "../components/Content";
import CreateFeatured from "../components/CreateFeatured";
import Demo from "../components/Demo";
import Featured from "../components/Featured";
import FeaturedContent from "../components/FeaturedContent";

const data ={
  id: 1,
  title1: 'Create with Deepsync',
  para1: 'Deepsync syncs your voice and lets you create short form audio with just scripts saving not only time but also production costs.',
  img1: '/images/Frame1.png'
}
const datas= [
  {id: 2,
  title1: 'Grow & Engage with Deepsync',
  para1: 'Deepsync lets you share your voice across channels in high quality and helps you analyze and grow your listener base.',
  img1: '/images/Frame2.png'
},
]

export default function Home() {
  return (
    <>
      <Head>
        <title>Deepsync Technologies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Featured />
      <CreateFeatured  data={data} />
        <Content/>
      <CreateFeatured  datas={datas}/>
      <FeaturedContent/>
      <Analytics/>
      <Demo/>
        
    </>
  );
}
